<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.routes.default' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/routing/RouteCollection.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Routing/FilteredRouteCollectionBuilder.php';

return $this->services['nelmio_api_doc.routes.default'] = (new \Nelmio\ApiDocBundle\Routing\FilteredRouteCollectionBuilder(array('path_patterns' => array(0 => '^/users', 1 => '^/oauth', 2 => '^/signup', 3 => '^/api', 4 => '^/documentation', 5 => '^/login', 6 => '^/login_check', 7 => '^/logout', 8 => '^/profile', 9 => '^/register'), 'host_patterns' => array())))->filter(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}->getRouteCollection());
